# Generated by Django 5.2.1 on 2025-05-30 16:23

import problems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=problems.models.problem_file_upload_path),
        ),
    ]
