# Generated by Django 5.2.1 on 2025-05-31 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_problem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='semester',
        ),
    ]
