# Generated by Django 5.2.1 on 2025-06-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_remove_problem_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
