# Generated by Django 5.2 on 2025-04-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
