# Generated by Django 5.2 on 2025-05-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='type',
            field=models.CharField(choices=[('unsolved', 'Nierozwiązane'), ('solved', 'Rozwiązane'), ('verified', 'Sprawdzone')], default='unsolved', max_length=16),
        ),
    ]
