# Generated by Django 5.2 on 2025-05-14 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        ('submissions', '0002_problem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_solutions', to='problems.problem'),
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
