# Generated by Django 5.2 on 2025-05-19 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        ('submissions', '0003_alter_solution_problem_delete_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='title',
            field=models.CharField(default='Rozwiązanie', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='problems.problem'),
        ),
    ]
