# Generated by Django 5.2 on 2025-05-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_solution_description_solution_title_solution_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='title',
            field=models.CharField(default='Rozwiązanie', max_length=255),
        ),
    ]
