# Generated by Django 5.2 on 2025-05-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_alter_solution_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
