# Generated by Django 5.2 on 2025-05-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_alter_solution_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='helpful',
            field=models.BooleanField(default=False),
        ),
    ]
