# Generated by Django 5.2 on 2025-05-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_remove_solution_votes_solutionvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionvote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')], null=True),
        ),
    ]
