# Generated by Django 5.2 on 2025-05-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0009_alter_solutionvote_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solutionvote",
            name="value",
            field=models.SmallIntegerField(
                choices=[(1, "up"), (-1, "down")], null=True
            ),
        ),
    ]
