# Generated by Django 5.2.1 on 2025-05-30 16:23

import submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_alter_solutionvote_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=submissions.models.solution_file_upload_path),
        ),
    ]
