# Generated by Django 5.2.1 on 2025-05-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_alter_solution_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='file',
            field=models.FileField(blank=True, max_length=600, null=True, upload_to='solutions/'),
        ),
    ]
