# Generated by Django 5.2.1 on 2025-05-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_alter_solution_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
