# Generated by Django 5.2.1 on 2025-07-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_alter_solution_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
