# Generated by Django 5.1.7 on 2025-04-02 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mathproarticle',
            old_name='link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='material',
            name='subject',
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='materials.subject')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='materials.topic'),
        ),
        migrations.AddField(
            model_name='mathproarticle',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mathpro_articles', to='materials.topic'),
        ),
    ]
