# Generated by Django 5.2 on 2025-04-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_topic_slug_topic_unique_topic_slug_per_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('official', 'Oficjalne'), ('student_notes', 'Notatki'), ('mathpro', 'MathPro')], max_length=20),
        ),
    ]
