# Generated by Django 5.1.7 on 2025-04-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_subject_slug_topic_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='material',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
