# Generated by Django 5.1.7 on 2025-04-06 13:41

import materials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_rename_description_material_short_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mathproarticle',
            old_name='description',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, upload_to=materials.models.material_upload_path),
        ),
    ]
