# Generated by Django 5.1.7 on 2025-04-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_rename_description_mathproarticle_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='material_type',
            new_name='type',
        ),
    ]
