# Generated by Django 5.1.7 on 2025-04-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_rename_material_type_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('official', 'Oficjalne'), ('student_notes', 'Notatki')], max_length=20),
        ),
    ]
