# Generated by Django 5.2.1 on 2025-05-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(choices=[('I', 'Licencjat / Inżynier'), ('II', 'Magister')], max_length=2, verbose_name='Stopień studiów')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Numer semestru')),
            ],
            options={
                'verbose_name': 'Semestr',
                'verbose_name_plural': 'Semestry',
                'ordering': ['degree_type', 'number'],
                'unique_together': {('degree_type', 'number')},
            },
        ),
    ]
