# Generated by Django 5.2.1 on 2025-05-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['degree_type', 'number']},
        ),
        migrations.AlterField(
            model_name='semester',
            name='degree_type',
            field=models.CharField(choices=[('I', 'Licencjat / Inżynier')], max_length=2),
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
