# Generated by Django 5.2 on 2025-05-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='short_description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('official', 'Oficjalne'), ('student_notes', 'Notatki'), ('mathpro', 'MathPro')], default='student_notes', max_length=20),
        ),
    ]
