# Generated by Django 5.2 on 2025-05-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_rename_short_description_material_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('official', 'Oficjalne'), ('student_notes', 'Notatki'), ('article', 'Artykuł')], default='student_notes', max_length=20),
        ),
    ]
