# Generated by Django 5.2.1 on 2025-05-31 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_semester'),
        ('materials', '0003_alter_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='curriculum.semester', verbose_name='Semestr'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, max_length=600, null=True, upload_to='materials/'),
        ),
    ]
