# Generated by Django 5.2 on 2025-05-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_material_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="semester",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Semestr 1"),
                    (2, "Semestr 2"),
                    (3, "Semestr 3"),
                    (4, "Semestr 4"),
                    (5, "Semestr 5"),
                    (6, "Semestr 6"),
                    (7, "Semestr 7"),
                    (8, "Semestr 8"),
                ],
                null=True,
            ),
        ),
    ]
