# Generated by Django 5.2.1 on 2025-05-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_material_semester_alter_material_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
